"""Recipes — an ordered list of steps, and the loop that runs it.

A recipe is the workflow's authored artefact: the sequence of operations a model
is put through, held as data so it can be inspected, edited, diffed, re-run and
handed on.  It is deliberately **just a list**: steps run in the order written
and no dependency graph is inferred, which is the same choice the analysis layer
makes — results are composed explicitly by the caller, not by machinery.

There are two serialisations of one meaning:

* :meth:`Recipe.to_dict` / :meth:`Recipe.from_dict` (and :meth:`Recipe.to_json`
  / :meth:`Recipe.from_json`) is the **editable form** — a plain tree of
  strings, numbers, lists and mappings.  It is what the GUI's pipeline panel
  reads and writes, and it round-trips losslessly.
* :meth:`Recipe.to_python` emits the same recipe as a **runnable script**, so a
  workflow assembled by clicking can be taken away as code.

The model a recipe prepares is never mutated by the run: a step that edits
properties copies it first (see
:mod:`fea_toolkit.workflow.verbs.scale_sections`).
"""

import copy
import json
from dataclasses import dataclass, field
from pprint import pformat
from typing import Any, Optional

from ..model.selection import Selection

__all__ = ["Recipe", "RecipeRun", "run_recipe"]

_HEADER = '"""A workflow recipe, generated by fea_toolkit.workflow."""'


def _step_to_dict(step: Any) -> dict:
    """Serialise one step, keeping an absent selection distinct from an empty one.

    Args:
        step: The :class:`~fea_toolkit.workflow.steps.Step` to serialise.

    Returns:
        A JSON-native mapping.  ``selection`` is the selection expression, or
        ``None`` for "no selection at all" — an empty *expression* stays ``""``,
        because the two mean different things to a verb.
    """
    return {
        "verb": step.verb,
        "selection": step.selection.to_string() if step.selection is not None else None,
        "params": copy.deepcopy(step.params),
        "optional": bool(step.optional),
    }


@dataclass
class Recipe:
    """An ordered list of steps, with a name for display and provenance.

    Attributes:
        steps: The steps, in run order.
        name: Display name, e.g. ``"Admin Building — gravity"``.
    """

    steps: list = field(default_factory=list)
    name: str = ""

    def add(
        self,
        verb: str,
        selection: Any = None,
        params: Optional[dict] = None,
        *,
        optional: bool = False,
    ) -> Any:
        """Append a step and return it.

        Args:
            verb: The verb to add; must be a key of ``STEP_SPECS``.
            selection: The elements the step acts on, or ``None`` for all.
            params: Verb parameters; omissions take their declared defaults.
            optional: Whether a failure of this step should be tolerated.

        Returns:
            The appended :class:`~fea_toolkit.workflow.steps.Step`.

        Raises:
            ValueError: If *verb* is unknown, or a parameter is undeclared or
                has the wrong type.
        """
        from .registry import STEP_SPECS
        from .steps import Step

        if verb not in STEP_SPECS:
            raise ValueError(f"unknown verb {verb!r}; known verbs: {sorted(STEP_SPECS)}")
        # Type-check now, so a mistake surfaces where it was made rather than
        # at the end of a long run.
        STEP_SPECS[verb].validate(params or {})
        step = Step(verb=verb, selection=selection, params=dict(params or {}), optional=optional)
        self.steps.append(step)
        return step

    # ── Serialisation ────────────────────────────────────────────────

    def to_dict(self) -> dict:
        """The recipe as a JSON-native mapping of the edits actually made.

        Only the parameters a step sets are written, so a file stays readable
        and a round-trip is faithful — defaults are applied at run time, not
        baked into the file.

        Returns:
            ``{"name": str, "steps": [...]}``.
        """
        return {"name": self.name, "steps": [_step_to_dict(step) for step in self.steps]}

    @classmethod
    def from_dict(cls, data: dict) -> "Recipe":
        """Rebuild a recipe from :meth:`to_dict` output.

        Args:
            data: The mapping to read.  ``steps`` may be absent (an empty
                recipe); every step's verb and parameters are validated here,
                so an invalid recipe fails on load rather than mid-run.

        Returns:
            The rebuilt recipe.

        Raises:
            ValueError: If *data* is not a mapping, a step is not a mapping, a
                verb is unknown, a parameter is undeclared, or a value has the
                wrong type.
        """
        from .registry import STEP_SPECS
        from .steps import Step

        if not isinstance(data, dict):
            raise ValueError(f"a recipe must be a mapping, got {type(data).__name__}")
        steps = []
        for index, raw in enumerate(data.get("steps") or []):
            if not isinstance(raw, dict):
                raise ValueError(
                    f"recipe step {index}: expected a mapping, got {type(raw).__name__}"
                )
            verb = raw.get("verb")
            if verb not in STEP_SPECS:
                raise ValueError(
                    f"recipe step {index}: unknown verb {verb!r}; known verbs: {sorted(STEP_SPECS)}"
                )
            spec = STEP_SPECS[verb]
            given = dict(raw.get("params") or {})
            for name, value in given.items():
                if name not in spec.params:
                    raise ValueError(
                        f"recipe step {index} ({verb}): unknown parameter {name!r}; "
                        f"expected {sorted(spec.params)}"
                    )
                spec.params[name].coerce(value, verb=verb, name=name)
            expression = raw.get("selection")
            selection = Selection.from_string(expression) if expression is not None else None
            steps.append(
                Step(
                    verb=verb,
                    selection=selection,
                    params=given,
                    optional=bool(raw.get("optional", False)),
                )
            )
        return cls(steps=steps, name=str(data.get("name", "")))

    def to_json(self, path: Optional[str] = None) -> str:
        """Serialise to JSON, optionally writing it to *path*.

        Args:
            path: Where to write the JSON.  ``None`` just returns the text.

        Returns:
            The JSON text — the same text written when *path* is given.
        """
        text = json.dumps(self.to_dict(), indent=2)
        if path is not None:
            with open(path, "w", encoding="utf-8") as handle:
                handle.write(text + "\n")
        return text

    @classmethod
    def from_json(cls, path: str) -> "Recipe":
        """Read a recipe written by :meth:`to_json`.

        Args:
            path: The JSON file to read.

        Returns:
            The rebuilt recipe.

        Raises:
            ValueError: If the file does not hold a recipe, or a step is invalid.
        """
        with open(path, encoding="utf-8") as handle:
            return cls.from_dict(json.loads(handle.read()))

    def to_python(self) -> str:
        """Emit the recipe as a runnable Python script.

        The script rebuilds the same recipe through :meth:`from_dict` and runs
        it, so a workflow assembled in the GUI can be taken away as code and
        kept under version control.

        Returns:
            The script source.  It compiles (``compile()`` succeeds) and, with
            a real model path, runs.
        """
        body = pformat(self.to_dict(), width=88, sort_dicts=False)
        return (
            _HEADER
            + "\n\n"
            + "from fea_toolkit.io.s2k_parser import SAP2000Parser\n"
            + "from fea_toolkit.workflow import Recipe, run_recipe\n\n"
            + "#: The model this recipe prepares.\n"
            + 'MODEL_PATH = "model.s2k"\n\n'
            + "#: The same declarative form Recipe.to_dict() writes.\n"
            + f"RECIPE = {body}\n\n\n"
            + "def main() -> None:\n"
            + "    md = SAP2000Parser(MODEL_PATH).parse().get_model_data()\n"
            + "    run = run_recipe(Recipe.from_dict(RECIPE), md, log=print)\n"
            + "    for result in run.results:\n"
            + '        print(f"{result.kind}: {result.label}")\n\n\n'
            + 'if __name__ == "__main__":\n'
            + "    main()\n"
        )

    def __len__(self) -> int:
        return len(self.steps)

    def __iter__(self):
        return iter(self.steps)


@dataclass
class RecipeRun:
    """What a recipe run produced, in step order.

    Attributes:
        results: Every :class:`~fea_toolkit.workflow.steps.StepResult` the run
            produced, in step order.  A step may contribute several.
        failures: ``(step index, verb, message)`` for each *optional* step that
            failed and was tolerated.  A non-optional failure does not appear
            here — it raises :class:`~fea_toolkit.workflow.steps.StepError`, so
            the run cannot end with a silently-different model.
        cancelled: Whether the run stopped early because ``cancel()`` asked it to.
    """

    results: list = field(default_factory=list)
    failures: list = field(default_factory=list)
    cancelled: bool = False


def run_recipe(
    recipe: Recipe,
    model_data: Any,
    *,
    model: Any = None,
    cancel: Any = None,
    log: Any = None,
) -> RecipeRun:
    """Run a recipe's steps in order against *model_data*.

    Each step sees the state the previous one left: a meshing step's topology is
    what a later analysis step solves, and an analysis step's cases are what a
    later reduction step reads.  ``cancel()`` is polled **between** steps — a
    step already running is never interrupted mid-way, matching the GUI worker's
    cooperative cancellation.  A step that stops *itself* mid-way (a solve
    cancelled between cases) records it on ``context.cancelled``, which is read
    after every step — including the last — so the run is still reported
    cancelled.

    Args:
        recipe: The steps to run.
        model_data: The parsed model to prepare.  It is not mutated: a step that
            edits properties works on a copy.
        model: An already-prepared topology to start from, if there is one.
        cancel: Zero-argument predicate; ``True`` stops the run at the next step
            boundary.  Defaults to "never cancelled".
        log: One-line sink for progress.  Defaults to discarding messages.

    Returns:
        The :class:`RecipeRun` — its results, tolerated failures and whether it
        was cancelled.

    Raises:
        StepError: If a non-optional step raises.  The error carries the step's
            index, its verb and the original exception.
        ValueError: If a step names an unknown verb.
    """
    from .registry import STEP_SPECS
    from .steps import CASES, FIGURE, GEOMETRY, MODAL, StepContext, StepError

    context = StepContext(model_data=model_data, model=model)
    if cancel is not None:
        context.cancel = cancel
    if log is not None:
        context.log = log

    # A caller-supplied topology counts as produced geometry, so a recipe may
    # start with an analysis step when run_recipe is handed an already-prepared
    # ``MeshModel``.  Every successful step adds its kind here; a step's
    # ``needs`` is validated against it before the step runs.
    produced = {GEOMETRY} if model is not None else set()

    run = RecipeRun()
    for index, step in enumerate(recipe.steps):
        if context.cancel():
            run.cancelled = True
            context.log(f"recipe: cancelled before step {index} ({step.verb})")
            break
        spec = STEP_SPECS.get(step.verb)
        if spec is None:
            raise ValueError(
                f"recipe step {index}: unknown verb {step.verb!r}; "
                f"known verbs: {sorted(STEP_SPECS)}"
            )
        missing = [kind for kind in spec.needs if kind not in produced]
        try:
            if missing:
                raise ValueError(
                    f"step {index} ({step.verb}) needs {missing[0]!r} — "
                    f"run a step that produces {missing[0]!r} first"
                )
            run.results.extend(spec.run(context, step))
            produced.add(spec.kind)
            if spec.kind == GEOMETRY:
                # A meshing step replaced ``context.model``, so the results the
                # previous topology produced — solved cases, a modal result and
                # any chart — are stale.  Drop them from ``produced`` so a later
                # step's ``needs`` is re-validated against the new mesh, and
                # clear their context slots so nothing reads a stale payload.
                produced.difference_update((CASES, MODAL, FIGURE))
                context.case_results.clear()
                context.results.clear()
        except Exception as exc:
            if not step.optional:
                raise StepError(index, step.verb, exc) from exc
            message = f"{type(exc).__name__}: {exc}"
            run.failures.append((index, step.verb, message))
            context.log(
                f"recipe: step {index} ({step.verb}) failed and is optional — continuing: {message}"
            )
        if context.cancelled:
            # A step that stopped mid-way (a solve cancelled between cases)
            # reports it on the context, so the run is marked cancelled even
            # when that step was the last one.
            run.cancelled = True
            break
    return run
