#!/usr/bin/env python3
"""Auto-generate docs/documentation_index.md from YAML frontmatter.

Scans all *.md files in this directory, parses their YAML frontmatter,
and produces a categorised index grouped by ``category`` (in display order).

Usage:
    python docs/_generate_index.py

Output:
    docs/documentation_index.md  (overwritten)
"""

import re
from pathlib import Path

DOCS_DIR = Path(__file__).parent
INDEX_PATH = DOCS_DIR / "documentation_index.md"

# ── Category display settings ────────────────────────────────────

CATEGORIES = [
    ("core-pipeline", "🚀 Core Pipeline"),
    ("analysis-types", "🔬 Analysis Types"),
    ("model-features", "⚙️ Model Features"),
    ("export-viz", "🎨 Export & Visualisation"),
    ("tool-specific", "🛠️ Tool-Specific Workflows"),
    ("planning", "📋 Planning & Historical"),
]

STATUS_BADGE = {
    "complete": "✅ Complete",
    "stable": "✅ Complete",
    "partial": "⚠️ Partial",
    "draft": "🚧 Draft",
    "placeholder": "🚧 Placeholder",
}

HEADER = """# Documentation Index

> Auto-generated by `_generate_index.py`. Do not edit manually.

This index provides a single entry point to all documentation. Each file
includes YAML frontmatter with `tags`, `category`, and `related` fields
for automated cross-referencing.

---

"""

FOOTER = """---

## Tag Index

Tags across all documentation files:

{{TAGS_TABLE}}

To regenerate this index, run:

```bash
python docs/_generate_index.py
```
"""


def parse_frontmatter(content: str) -> dict:
    """Extract YAML frontmatter as a dict. Returns empty dict if not found."""
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
    if not m:
        return {}
    block = m.group(1)
    fm = {}
    for line in block.splitlines():
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip().strip('"').strip("'")
        if val.startswith("[") and val.endswith("]"):
            val = [v.strip().strip('"').strip("'") for v in val[1:-1].split(",")]
        fm[key] = val
    return fm


def get_tag_map(docs: list[tuple[str, dict]]) -> dict[str, list[str]]:
    """Build {tag: [filename, ...]} mapping."""
    tag_map: dict[str, list[str]] = {}
    for fname, fm in docs:
        tags = fm.get("tags", [])
        if isinstance(tags, str):
            tags = [t.strip() for t in tags.split(",")]
        for t in tags:
            tag_map.setdefault(t, []).append(fname)
    return tag_map


def main():
    md_files = sorted(DOCS_DIR.glob("*.md"))
    docs: list[tuple[str, dict]] = []

    for f in md_files:
        if f.name.startswith("_") or f.name in ("README.md", "documentation_index.md", "index.md"):
            continue
        content = f.read_text(encoding="utf-8")
        fm = parse_frontmatter(content)
        docs.append((f.name, fm))

    # Group by category
    cat_docs: dict[str, list[tuple[str, dict]]] = {}
    for fname, fm in docs:
        cats = fm.get("category", ["uncategorised"])
        if isinstance(cats, str):
            cats = [cats]
        for c in cats:
            cat_docs.setdefault(c, []).append((fname, fm))

    # Build output
    lines = [HEADER]

    # ── Category sections ──
    by_priority = {key: label for key, label in CATEGORIES}
    displayed_cats = [c for c, _ in CATEGORIES]
    remaining = [c for c in cat_docs if c not in by_priority]

    for cat_key in displayed_cats + remaining:
        if cat_key not in cat_docs:
            continue
        label = by_priority.get(cat_key, f"📦 {cat_key.replace('-', ' ').title()}")
        lines.append(f"## {label}\n")
        docs_in_cat = sorted(cat_docs[cat_key], key=lambda x: x[0])
        for fname, fm in docs_in_cat:
            title = fm.get("title", fname.replace(".md", "").replace("_", " ").title())
            desc = fm.get("description", "")
            status = fm.get("status", "")
            badge = STATUS_BADGE.get(status, "")
            badge_str = f" — {badge}" if badge else ""
            link = fname
            lines.append(f"- [{title}]({link}){badge_str}")
            if desc:
                lines.append(f"  > {desc}")
            tags = fm.get("tags", [])
            if isinstance(tags, str):
                tags = [t.strip() for t in tags.split(",")]
            if tags and tags[0]:
                lines.append(f"  Tags: `{'`, `'.join(tags)}`")
            related = fm.get("related", [])
            if isinstance(related, str):
                related = [r.strip() for r in related.split(",")]
            if related and related[0]:
                related_links = []
                for r in related:
                    r_title = ""
                    for rf, rfm in docs:
                        if rf == r:
                            r_title = rfm.get("title", rf)
                            break
                    if r_title:
                        related_links.append(f"[{r_title}]({r})")
                    else:
                        related_links.append(f"[{r}]({r})")
                lines.append(f"  Related: {' · '.join(related_links)}")
            lines.append("")
        lines.append("")

    # ── Tag index ──
    tag_map = get_tag_map(docs)
    tag_lines = []
    for tag in sorted(tag_map):
        linked = ", ".join(f"[{f}]({f})" for f in sorted(tag_map[tag]))
        tag_lines.append(f"- **`{tag}`** — {linked}")
    tag_section = "\n".join(tag_lines)
    footer = FOOTER.replace("{{TAGS_TABLE}}", tag_section)
    lines.append(footer)

    # Write
    output = "\n".join(lines) + "\n"
    INDEX_PATH.write_text(output, encoding="utf-8")
    num_docs = len(docs)
    num_tags = len(tag_map)
    print(f"✔ Generated {INDEX_PATH} ({num_docs} docs, {num_tags} tags)")


if __name__ == "__main__":
    main()
